cloudfoundry/bosh-agent

bin/build, bin/build-linux-ppc64le, bin/env
Hey, all.
Currently I run bosh-agent on a Power platform and it needs several changes to `bin/build` script. Building bosh-agent with gccgo requires specific environment setup and I am sure that this process should be moved to a separate file. 
Another goal of this PR is to build bosh-agent binary statically, which will allow to use it without having gccgo inside every stemcell.
=> [Power Support] Make a separate script to build bosh-agent on Power platform.

platform/disk/root_device_partitioner.go, platform/disk/root_device_partitioner_test.go, platform/linux_platform.go, platform/linux_platform_test.go
Function findRootDevicePath in platform/linux_platform.go requires
that root partition must be the first one. It can't be satisfied on
some platforms, for example on POWER (ppc64le).
This fix eliminates this requirement by detecting next available
partition id for /swap and /data instead hardcoded 2 and 3
respectively.
Signed-off-by: Alexander Lomov <alexander.lomov@altoros.com>
=> Eliminate “root partition must be the first one”

agent/action/concrete_factory_test.go, agent/action/drain.go, agent/action/drain_test.go, agent/action/run_script_test.go, agent/script/concrete_job_script_provider.go, agent/script/drain/concrete_script.go, agent/script/drain/concrete_script_test.go, agent/script/drain/fakes/fake_script.go, agent/script/fakes/fake_job_script_provider.go, agent/script/fakes/fake_script.go, agent/script/parallel_script.go, agent/script/parallel_script_test.go, agent/script/script_interface.go, vendor/github.com/cloudfoundry/bosh-utils/system/fakes/fake_cmd_runner.go
This fix makes drain action cancellable. It also introduces
CancellableScript interface and its implementation for drain and
parallel scripts.
Small change in fake_cmd_runner was made to propely test parallel async
execution of scripts.
[#106642152] (https://www.pivotaltracker.com/story/show/106642152)
Signed-off-by: Yulia Gaponenko <yulia.gaponenko@ru.ibm.com>
=> User can cancel while drain agent action is running

bin/build
On ppc64le platform sometimes we have to run 'develop' version of Go, may be
applicable  to x64 in some cases. We should
not to restrict a user in this case, a warning is enough.
Signed-off-by: Yulia Gaponenko <yulia.gaponenko@ru.ibm.com>
=> Allow build with 'develop' Go version

micro/https_handler.go
This commit  makes `micro/https_hander.go` show a reasonable error when failed to load agent SSL cert file (agent.cert).
=> Catch error from http dispatcher

app/config_test.go, platform/linux_platform.go, platform/linux_platform_test.go
+ The Micropcf team needs this option in order to use the an updated bosh-agent with bosh-provisioner and packer-bosh
=> Add SkipDiskSetup option to allow disk partitioning to be skipped on linux

platform/dummy_platform.go
Since the mountpoint check was moved to platofrm. Dummy platform
also needs to be updated.
=> Fix MountPersistentDisk in dummy platform

infrastructure/devicepathresolver/id_device_path_resolver.go, infrastructure/devicepathresolver/id_device_path_resolver_test.go, infrastructure/http_metadata_service.go, infrastructure/http_metadata_service_test.go, infrastructure/settings_source_factory.go, infrastructure/settings_source_factory_test.go, platform/linux_platform.go, platform/provider.go
**Warning:** this should be merged at the same time as https://github.com/cloudfoundry/bosh/pull/1189 to avoid breaking AWS and OpenStack stemcell building.
Since the metadata service in Google Compute Engine has different paths than AWS or OpenStack for the instance user data, we need to allow the agent to take in the instance user data path, the instance ID path, and the SSH keys path in agent env HTTP sources.
Also, GCE uses "google" as the virtio device prefix, so we must allow this to be configurable as well.
=> Allow HTTP Metadata URLs and virtio device prefixes to be configurable

httpsdispatcher/https_dispatcher.go, httpsdispatcher/https_dispatcher_test.go
- We received the following error message when running unit tests on OSX
using Golang 1.6:
http2: TLSConfig.CipherSuites index 2 contains an HTTP/2-approved
cipher suite (0xc02f), but it comes after unapproved cipher suites.
With this configuration, clients that don't support previous, approved
cipher suites may be given an unapproved one and reject the
connection.
- Re-ordered the CipherSuites to match the list in Golang source:
https://github.com/golang/go/blob/dc5a7682f0ec9cc344fcdb61d67b9d37c6ad3cc6/src/crypto/tls/cipher_suites.go#L75-L95
[#116463189](https://www.pivotaltracker.com/story/show/116463189)
Signed-off-by: Lyle Franklin <lfranklin@pivotal.io>
=> Re-order CipherSuites to avoid http2 error message

app/config_test.go, infrastructure/http_metadata_service.go, infrastructure/instance_metadata_settings_source.go, infrastructure/instance_metadata_settings_source_test.go, infrastructure/metadata_service_interface.go, infrastructure/settings_source_factory.go
This change creates a settings source named `InstanceMetadata` that retrieves and unmarshals BOSH settings from a URI on the instance's metadata store. Google Compute Engine supports mutable instance metadata and this will be used in conjunction with the [Google CPI](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/tree/metadata-registry) to eliminate the registry when using Google Cloud Platform.
=> New Settings Source: Instance metadata

platform/net/dns_validator.go, platform/net/dns_validator_test.go
This might happen when the DNS servers in the manifest for some reason didn't make it to `/etc/resolv.conf`
=> More descriptive error when /etc/resolv.conf content doesn't match

platform/provider.go
At 500ms, the device resolver timeout is too aggressive for some cloud deployments.
=> Increase disk resolver timeout for Bracker computing

platform/linux_platform.go, platform/linux_platform_test.go
Since for `ppc64le` architecture device number is not `1` by default the code use value returned from root device finder
Signed-off-by: Yulia Gaponenko <yulia.gaponenko@ru.ibm.com>
=> Replace hardcoded device number to value returned by root device finder

platform/disk/parted_partitioner.go, platform/disk/parted_partitioner_test.go
Signed-off-by: Tanzeeb Khalili <tkhalili@pivotal.io>
`parted -m` exits with 0 on centos. Fix checks stderr instead of error objects.
=> fixes formatting using parted on centOS

app/app.go
previously they were sent every 60s, which is dangerous with the default BOSH HM agent timeout of 60s.
=> Send heartbeats every 30s

infrastructure/devicepathresolver/id_device_path_resolver.go, infrastructure/devicepathresolver/id_device_path_resolver_test.go
- the Agent was not properly following the devices' links
- the tests were falsely returning the target of the link instead of the matching fileglobs (fixed)
- error checking in the tests is more stringent (unrelated)
- may affect other IaaSes
fixes:
```
Command 'deploy' failed:
Deploying:
Creating instance 'bosh/0':
Updating instance disks:
Updating disks:
Deploying disk:
Mounting disk:
Sending 'get_task' to the agent:
Agent responded with error: Action Failed get_task: Task d5818063-217f-41e3-5110-01a5539d86d2 result: Mounting persistent disk: Formatting partition with : Checking filesystem format of partition: Running command: 'blkid -p /dev/disk/by-id/virtio-7c6dadc7-3231-4f60-a1', stdout: '', stderr: 'error: /dev/disk/by-id/virtio-7c6dadc7-3231-4f60-a1: No such file or directory
``` …
=> OpenStack successfully partitions persistent disks

agent/action/ssh.go, agent/action/ssh_test.go, agent/bootstrap.go, agent/bootstrap_test.go, docs/dev_setup.md, platform/dummy_platform.go, platform/fakes/fake_platform.go, platform/linux_platform.go, platform/linux_platform_test.go, platform/platform_interface.go, platform/windows_platform.go, settings/settings.go, settings/settings_test.go
- Makes generation of authorized SSH keys more consistent
across different IaaS
- Still allows agent to get public keys from IaaS, e.g. `/openssh-key` on AWS,
keys specified in `env` are appended to these keys
**Important:** Make sure to bump bosh-agent submodule in bosh repo.
Signed-off-by: Mark Fussell <mfussell@pivotal.io>
[#130786799](https://www.pivotaltracker.com/story/show/130786799)
=> Agent will add authorized keys from `env`

infrastructure/http_metadata_service.go, infrastructure/http_metadata_service_test.go, infrastructure/instance_metadata_settings_source.go, infrastructure/instance_metadata_settings_source_test.go, jobsupervisor/pipe/winsw_pipe_suite_test.go
Each request to the metadata service is now potentially retried up to 10 times with a delay of 1 second, if the response is non-2xx. We reused the client retryable that is also used to check monit status for this.
The change affects at least the AWS, Google and OpenStack stemcell's metadata retrieval.
@evandbrown @ljfranklin @cppforlife Please let us know, if this a problem. At least for the Google CPI, which wraps the metadata service, this behavior could be deactivated.
[#133431439](https://www.pivotaltracker.com/story/show/133431439)
=> Retry metadata service request

infrastructure/complex_settings_source.go, infrastructure/http_metadata_service.go, infrastructure/http_metadata_service_test.go, infrastructure/http_registry.go, infrastructure/http_registry_test.go, infrastructure/registry_provider.go, infrastructure/registry_provider_test.go, infrastructure/settings_source_factory_test.go, jobsupervisor/monit/monit_retry_client.go
This change requires changes introduced to bosh-utils: https://github.com/cloudfoundry/bosh-utils/pull/8. Please merge that one first, and bump bosh-utils in bosh-agent before merging this PR.
- make fetching from registry settings more
resilient by using the RetryClient
- retry 10 times with 1s delay
[#135338075](https://www.pivotaltracker.com/story/show/135338075)
Signed-off-by: Beyhan Veli <beyhan.veli@sap.com>
=> Registry settings fetcher retries on failure

agent/bootstrap.go, agent/bootstrap_test.go, platform/dummy_platform.go, platform/fakes/fake_platform.go, platform/linux_platform.go, platform/linux_platform_test.go, platform/net/centos_net_manager.go, platform/net/fakes/fake_net_manager.go, platform/net/net_manager_interface.go, platform/net/ubuntu_net_manager.go, platform/net/ubuntu_net_manager_test.go, platform/net/windows_net_manager.go, platform/platform_interface.go, platform/windows_platform.go, settings/settings.go, settings/settings_test.go
Users can force Ubuntu machines to enable IPv6 at the kernel level through agent setting:
```yaml
instance_groups:
- name: my-stuff
env:
bosh:
ipv6:
enable: true
```
=> allow enabling of ipv6 through env.bosh.ipv6.enable=true

docs/dev_setup.md
bosh-cli has merged support for using GCS as a director blobstore. BOSH director and the google CPI are merging support. The stemcell has an open PR for bosh-gcscli inclusion.
This change documents GCS is usable as a blobstore.
cloudfoundry/bosh#1732
cloudfoundry/bosh-cli#238
cloudfoundry-incubator/bosh-google-cpi-release#218
cloudfoundry/bosh-linux-stemcell-builder/pull/16
Do not merge until cloudfoundry-incubator/bosh-google-cpi-release#218, cloudfoundry/bosh#1732, and https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/16 are merged.
=> Document GCS as blobstore provider

agent/heartbeat_test.go, platform/stats/dummy_stats_collector.go, platform/stats/fakes/fake_stats_collector.go, platform/stats/stats_collector_interface.go, platform/vitals/service.go, platform/vitals/service_test.go, platform/vitals/vitals.go, sigar/sigar_stats_collector.go
vitals.uptime.secs field is added as expected by bosh-cli
[#146195069](https://www.pivotaltracker.com/story/show/146195069)
=> Add vm uptime information into vitals

agent/action/unmount_disk_test.go, platform/disk/diskutil.go, platform/disk/fakes/fake_mounter.go, platform/disk/linux_bind_mounter.go, platform/disk/linux_bind_mounter_test.go, platform/disk/linux_mounter.go, platform/disk/linux_mounter_test.go, platform/disk/mounter_interface.go, platform/dummy_platform.go, platform/dummy_platform_test.go, platform/linux_platform.go, platform/linux_platform_test.go, settings/settings.go, settings/settings_test.go
We'd like to be able to pass persistent disk mount options through the env, in a similar fashion to [the filesystem type](https://bosh.io/docs/persistent-disk-fs.html).
This commit adds the ability to do this, using the `env` key `persistent_disk_mount_options`. We (Garden+Groot team) want this feature to allow us to deploy xfs-formatted disks with project quotas enabled (without having to use loopback devices).
We ran `bin/test-unit` and `bin/test-integration`, and also kicked the tires on an AWS stemcell we built using the scripts in `bin/repack-stemcell`. If there's anything else we should run please let us know.
Cheers,
@callisto13 & Craig
=> Can pass mount options to persistent disk

infrastructure/http_metadata_service.go, infrastructure/http_metadata_service_test.go
The PR want to fix a defect that if there is no setting public ssh key, a 404 response error will happen while deploying cloud foundry. Public ssh key is optional for deployment CF and the error breaks up CF deployment.
The PR has a bosh-utils's [PR 41](https://github.com/cloudfoundry/bosh-utils/pull/41).
=> Fix 404 response error for getting public ssh key

infrastructure/devicepathresolver/iscsi_device_path_resolver.go, platform/openiscsi/concrete_open_iscsi_admin.go, platform/openiscsi/concrete_open_iscsi_admin_test.go, platform/openiscsi/fakes/fake_open_iscsi.go, platform/openiscsi/open_iscsi_interface.go
This PR worked on iscsiadm compatibility for xenial:
When using xenial, iscsiadm command returns error more explicit such as login when session already present:
```
/etc/iscsi# iscsiadm -m node -l
Logging in to [iface: default, target: iqn.1992-08.com.netapp:stflon0201, portal: 10.1.222.171,3260] (multiple)
Logging in to [iface: default, target: iqn.1992-08.com.netapp:stflon0201, portal: 10.1.222.172,3260] (multiple)
Login to [iface: default, target: iqn.1992-08.com.netapp:stflon0201, portal: 10.1.222.171,3260] successful.
Login to [iface: default, target: iqn.1992-08.com.netapp:stflon0201, portal: 10.1.222.172,3260] successful.
/etc/iscsi# iscsiadm -m node -l
iscsiadm: default: 1 session requested, but 1 already present.
iscsiadm: default: 1 session requested, but 1 already present. …
```
=> Fix iscsiadm compatibility for xenial.

Gopkg.lock, integration/assets/install-go.sh, integration/config_drive_test.go, integration/integration_suite_test.go, integration/test_environment.go, vendor/github.com/kevinburke/ssh_config/AUTHORS.txt, vendor/github.com/kevinburke/ssh_config/LICENSE, vendor/github.com/kevinburke/ssh_config/config.go, vendor/github.com/kevinburke/ssh_config/lexer.go, vendor/github.com/kevinburke/ssh_config/parser.go, vendor/github.com/kevinburke/ssh_config/position.go, vendor/github.com/kevinburke/ssh_config/token.go, vendor/github.com/kevinburke/ssh_config/validators.go, vendor/github.com/pelletier/go-buffruneio/buffruneio.go
This patch opens an SSH connection once at the start of the test suite rather than invoking `vagrant ssh` thousands of times. Each `vagrant ssh` has around one second of overhead which built up. The tests are 11x faster on my machine with this patch applied.
I had to change one test because it was expecting to be run in a shell environment with pipes. That was the only test which depended on that behavior.
=> Make integration tests 11x faster (44m -> 4m)

agentclient/http/agent_client.go
The format string was correct in the context of the informational line
but didn't have a placeholder for the error message added in the next
line.
Adding a '%s' to the first line would work but would confuse static
analysis tools which would detect it as a placeholder-to-argument
mismatch. Inlining everything results in a longer but overall simpler
line.
**Before**
```
[httpAgentClient] 2018/08/28 13:04:34 DEBUG - Error occured sending get_task. Error retry 1 of 10%!(EXTRA errors.ComplexError=Sending 'get_task' to the agent: Agent responded with error: Action Failed get_task: Task 42cfd353-5d4e-41ab-7adb-ea0894c13e74 result: Extracting method arguments from payload: Unmarshalling action argument: No digest algorithm found. Supported algorithms: sha1, sha256, sha512)
```
**After**
``` …
```
=> agentclient/http: fix retry format string

platform/net/ubuntu_net_manager.go, platform/net/ubuntu_net_manager_test.go, settings/service.go
This PR worked on configuring DNS servers for preconfigured networks.
We merged PR 151: https://github.com/cloudfoundry/bosh-agent/pull/151#issuecomment-381711516 and modified this code https://github.com/cloudfoundry/bosh-agent/blob/c74db775183f3e0e68254279e649b802bd4bf63f/platform/net/ubuntu_net_manager.go#L100-L103
It skipped configuring network alias interfaces and caused empty virtual interfaces. We should continue to configure networked after writing DNS entries. 
@mikexuu Please help to view about network configs.
=> DNS servers for preconfigured networks

platform/net/windows_net_manager.go, platform/net/windows_net_manager_test.go
We were running into a problem where after creating an HNS Network we were getting two network adapters returned for the same MAC address.
This was then causing the `netsh interface ip set` line of the NicSettingsTemplate powershell script to fail since it was combining the two names.
We tried this change out with a 2019 stemcell. It fixed our problem and seemed to otherwise work fine.
@ashwin-venkatesh
=> Simplify NicSettingsTemplate

agent/action/run_script.go, agent/action/run_script_test.go
This change updates `run_script` to take use a structured object for
options rather than an genreic map. This change should be both backwards
compatible and forwards compatible due to the unmarshalling behavior of
JSON in Golang. Adding fields to the options struct will be additive
changes and will not break older directors.
[#164262374](https://www.pivotaltracker.com/story/show/164262374)
=> Use a defined type rather for script options

infrastructure/multi_source_metadata_service.go, infrastructure/multi_source_metadata_service_test.go
When the bosh agent is initially starting on a VM, it seems that a race condition can occur where the `agent.json` will point to `ConfigDriveMetadataService` and a `FileMetadataService`, but neither the referenced drive nor the referenced file exist yet on the VM, and we get a nil pointer dereference error. The agent will eventually recover once the files/drive exist, but until then it makes for some nasty agent logs to read through, and led my team and I astray while we were trying to debug a different issue. 
```2019-03-21_22:41:44.27019 [main] 2019/03/21 22:41:44 DEBUG - Starting agent
2019-03-21_22:41:44.28267 [File System] 2019/03/21 22:41:44 DEBUG - Reading file /var/vcap/bosh/agent.json
2019-03-21_22:41:44.31884 [File System] 2019/03/21 22:41:44 DEBUG - Read content …
```
=> Fix nil deference error when no service is available

platform/cert/windows_cert_manager.go
https://stackoverflow.com/questions/55484185/object-or-property-already-exists-error-when-trying-to-export-certificate-from-r
Not sure why I am getting duplicate certs in my cert store. I have installed a private candidate KB from Microsoft, so I think that might have done something. The error I was seeing from compilation VMs without this fix was:
```
Error: Action Failed get_task: Task 1727f2f8-775a-4b78-7d6b-ef9622cc04be result: Running command: 'powershell -Command Get-ChildItem Cert:\LocalMachine\Root | Export-Certificate -Type SST -FilePath \var\vcap\data\tmp/rootCertBackup.sst', stdout: '', stderr: 'Export-Certificate : The object or property already exists. (Exception from HRESULT: 0x80092005)
At line:1 char:41
+ ... hine\Root | Export-Certificate -Type SST -FilePath …
```
=> Fix Windows cert manager backups when there are duplicate certs

platform/net/routes_searcher_unix.go, platform/net/routes_searcher_unix_test.go, platform/provider.go
In this fix, perform checking before consuming the route parsing results to avoid [panic issue](https://github.com/cloudfoundry/bosh-agent/issues/230).
=> Fix blackhole route parsing

platform/net/routes_searcher_unix.go, platform/net/routes_searcher_unix_test.go, platform/provider.go
Reverts cloudfoundry/bosh-agent#231
Original PR was targeting wrong branch.
=> Revert "Fix blackhole route parsing"

platform/disk/ephemeral_device_partitioner_test.go, platform/disk/parted_partitioner.go, platform/disk/parted_partitioner_test.go
When extending the size of a persistent disk _for the second time_ on vSphere, the operation fails with "...Creating partition using parted...". This commit addresses that error.
Our fix is to strategically run `partprobe`, which "informs the operating system kernel of partition table changes".
We believe the cause of this error is the manner in which vSphere detaches disks from VMs, which differ from the manner in which other IaaSes, specifically GCP, detach disks. vSphere does not signal to the OS that the disk has been removed, and the memory of the disk "lingers".
For example, running `lsblk -a` after the first resize (say from 1GB → 2GB), the new (larger) disk shows up as `/dev/sdd` and the old (smaller) disk shows up as `/dev/sdc`. This stands in sharp contrast to GCP, where the new …
=> Fix double-resize persistent disk on vSphere

infrastructure/http_metadata_service.go, infrastructure/http_metadata_service_test.go, infrastructure/instance_metadata_settings_source.go, infrastructure/settings_source_factory.go
Adds support for a new tokenPath field in agent.json
When this field is present, the agent will make a PUT request to that path to fetch a token before each AWS Instance Metadata Service call, and will include that token in a header when calling IMDS.
When the tokenPath is not specified, the agent behaves as before and uses IMDSv1.
It should also fall back to IMDSv1 if IMDSv2 is not available in the region. We're not sure if this exists, but we ran into similar problems recently with availability of gp3 disks in some regions.
This functionality being used is dependent on an update to the `agent.json` in the bosh linux stemcell builder which will be coming soon.
=> Add AWS IMDSv2 support

agent/bootstrap.go, agent/bootstrap_test.go, integration/test_environment.go, platform/dummy_platform.go, platform/linux_platform.go, platform/linux_platform_test.go, platform/platform_interface.go, platform/platformfakes/fake_platform.go, platform/windows_platform.go
Similar to what we do with /var/log, we've seen issues where
people are installing 3rd party software on stemcells using automation.
For example, the Microsoft OMI Agent.
This software gets installed into /var/opt and logs into /var/opt/omi/log.
This ends up filling up the root disk eventually and VMs need
to be recreated. This software has no configuration options to log
into /var/log (and it seems that logging into /var/opt/THING/log
may be the correct linux spot to log to)
While this is not the suggested way to install software
onto a stemcell, this type of software is often put there
by people not involved with Bosh lifecycles.
Signed-off-by: Joseph Palermo <jpalermo@pivotal.io>
=> This moves /var/opt to /var/vcap/data/root_opt

integration/user_permissions_test.go, platform/linux_platform.go, platform/linux_platform_test.go
Newer stemcells (e.g. Jammy) "leak" BOSH users because the BOSH Agent fails to delete the user when the session is finished because the user still has an open process. Specifically, systemd's [User Manager](https://wiki.archlinux.org/title/systemd/User), which spawns a process which runs as the user, takes an addtional 7 seconds (approximately) to exit after the user has terminated their session.
To address this, we forcibly delete the user (`userdel -f`) after their session has finished. This doesn't harm the remaining systemd process; the kernel doesn't require the owner of a running process to have an entry in `/etc/passwd`; the kernel cares about UIDs, not usernames.
Fixes, from `/var/vcap/bosh/log/current`:
```
2022-01-21_19:46:44.20137 {"exception":{"message":"Action Failed ssh: SSH …
```
=> 🐞 Don't "leak" (fail to delete) BOSH users

integration/test_environment.go, platform/linux_platform.go, platform/linux_platform_test.go
We've heard reports of additional agents being installed into `/opt` and filling up the root disk. `/opt` is empty by default so this should be a safe operation.
We changed the mount point for `/var/opt` from `/var/vcap/data/root_opt` to `/var/vcap/data/root_var_opt` to avoid name confusion. Since this is all on the ephemeral disk it shouldn't cause breakage when those paths change.
=> When mounting /var/opt to the ephemeral disk, also mount /opt

agent/httpblobprovider/blobstore_delegator/blobstore_delegator.go, agent/httpblobprovider/blobstore_delegator/blobstore_delegator_test.go, app/app.go
We experience intermittently failing Get request to fetch the blobs from an external blobstore due to network issues. To make the Get mechanism more resilient we introduce a retry strategy.
=> Retry mechanism for http_blob_provider

platform/disk/ephemeral_device_partitioner_test.go, platform/disk/parted_partitioner.go, platform/disk/parted_partitioner_test.go
See:
- https://util-linux.vger.kernel.narkive.com/u1AkqI6Q/patch-wipefs-add-force-option
NOTE: This fix is meant to resolve VM startup errors like the following, which resulted from failure to resize a partition (on RHEL 8.5):
```
2022-02-18_20:48:56.73277 [attemptRetryStrategy] 2022/02/18 20:48:56 DEBUG - Making attempt #0
2022-02-18_20:48:56.73278 [Cmd Runner] 2022/02/18 20:48:56 DEBUG - Running command 'wipefs -a /dev/sdb'
2022-02-18_20:48:56.73530 [Cmd Runner] 2022/02/18 20:48:56 DEBUG - Stdout:
2022-02-18_20:48:56.73532 [Cmd Runner] 2022/02/18 20:48:56 DEBUG - Stderr: wipefs: error: /dev/sdb: probing initialization failed: Device or resource busy
2022-02-18_20:48:56.73533 [Cmd Runner] 2022/02/18 20:48:56 DEBUG - Successful: false (1)
```
=> parted partitioner: Use `wipefs --force` when removing partitions.

platform/windows_platform_test.go
NOTE: Extends the changes in 9f03a0d8 to unfixed code in platform/windows_platform_test.go.
=> `golangci-lint` passes on test code

agent/agent.go, mbus/handler_provider.go, mbus/handler_provider_test.go, mbus/nats_handler.go, mbus/nats_handler_test.go
We are seeing intermittent unresponsive agents in following scenario:
- upgrade bosh-director
- right after upgrade is finished, start recreating a deployment
In some situations there seems to be a race condition in between
1. the old director going down
2. Agent on the VM retries sending heartbeets
3. new director comes up and get's deploy command issued. Sends ping to agent
4. ???? Currently unclear why at this point the agent has not yet reconnected to nats
5. director doesn't get a response and the deploy command fails.
the issue has been solved in CI by introducing a 3 minute wait after the upgrade 
of the director but we would like to get to the root cause of this. It seems that if 
the agent DID NOT crash and restart within BOSHs downtime, the connection is 
somehow in a bad state. …
=> Introduce error handling for nats disconnects and add logging handlers for nats connection issues

bin/test-unit
running the test script from a shell that targets a
director that also requires BOSH_ALL_PROXY to be set
makes tests fail with:
```
Unexpected error:
<errors.ComplexError>: {
Err: <*errors.errorString | 0xc0002be570>{
s: "Getting open ssh key from url http://127.0.0.1:40481/ssh-keys",
},
Cause: <errors.ComplexError>{
Err: <*errors.errorString | 0xc0002be550>{
s: "Performing GET request",
},
Cause: <*errors.errorString | 0xc0002be540>{
s: "Get \"http://127.0.0.1:40481/ssh-keys\": ssh: rejected: connect failed (Connection refused)",
},
},
}
Getting open ssh key from url http://127.0.0.1:40481/ssh-keys: Performing GET request: Get "http://127.0.0.1:40481/ssh-keys": ssh: rejected: connect failed (Connection refused)
occurred
```
this is at best confusing and at worst requires dev
time to …
=> make tests not fail if the env has BOSH_ALL_PROXY set

integration/windows/windows_test.go, jobsupervisor/windows_job_supervisor.go, jobsupervisor/winsvc/winsvc.go
once upon a time this was done to prevent issues with consul
since we're not using consul anymore, we do not rely on the
vm being recreated anymore and it should be safe to just
restart/reboot it. The underlying issues were caused by local
dns entries done for consul going missing and we're not
aware of any additional issues in that regard.
see #182212385 // #131643669 for more details / history
```
In consul_agent_windows prestart we set the primary DNS to be localhost
so that consul can resolve internal addresses, but the bosh deployment
manifest pulls in DNS config from cloud-config. This causes BOSH to
override that value at some point in the future. We saw this happening
on Stonetalon that had a windows vm deployed for a couple of weeks now.
We need to figure out a better way around …
```
=> remove deactivation of bosh agent service automatic starts [#182212385]

infrastructure/devicepathresolver/iscsi_device_path_resolver.go, infrastructure/devicepathresolver/iscsi_device_path_resolver_test.go
iSCSI device discovery could not be called a second time after disk partioning,
since code was refactored for IaaS-native disk resize.
Here we modify slightly the algorithm so that a never-mounted but
already-partitioned disk doesn't trigger any unnecessary iSCSI restart.
Fixes #252.
While working on this fix, I've reviewed other strategy classes implementing the `DevicePathResolver` interface. Conclusion is that only the iSCSI strategy is dependant on whether the disk device is partitioned or not, which leads to different results when called before or after partitioning.
=> Fix device discovery through iSCSI for SoftLayer

mbus/nats_handler.go
fix for https://github.com/cloudfoundry/bosh-agent/issues/289
- avoid arithmetic overflow with math.Pow and subsequent conversion to int64 (by limiting exponent to a safe value)
- add sanity check for reconnect delay to safeguard against negative values or zero
- add support for delay in non-integer seconds (by fixing how time.Duration() is used with time.Second)
- use more consistent naming of constants and variables
=> fix overflow bug in nats_handler.go / nats.CustomReconnectDelay()

.github/workflows/go.yml
This replaces a hardcode value.
=> golangci-lint action uses Golang version from go.mod

platform/linux_platform.go, platform/linux_platform_test.go
The following commit tried to fix the preservation of extended attributes when migrating disk data, however is not complete, as also the `--xattrs-include=*.*` parameter is required to achieve for example the preservation of capabilities: https://github.com/cloudfoundry/bosh-agent/commit/c3f558b4d705c0d78b624bfc2b378901d338600b
With this we try to finally fix the preservation of all extended attributes, such as capabilities for example.
Preservation of capabilities are for importance in PKS (Tanzu Kubernetes Grid Integrated Edition / TKGI), as Docker images are stored on persistent disks.
Whenever a Docker image includes a binary with some capabilities (for example nginx-ingress-controller), these capabilities, without this change, get lost after disk migrations, which prevents the …
=> Preserve extended attributes when migrating disk data

infrastructure/devicepathresolver/scsi_volume_id_device_path_resolver.go, infrastructure/devicepathresolver/scsi_volume_id_device_path_resolver_test.go
We've gotten reports of intermittent agent_timed outs for deployments on vsphere with jammy stemcells (though it should also apply to bionic stemcells because it is caused by a change in the kernel) 
These we're caused by the agent failing to setup the ephemeral disk attached to the VM because the resolver code never entered the if statement: `if path.Base(rootDevicePath) == "sda"`
Investigation on the VM showed that:
`ls /sys/bus/scsi/devices/32:0:0:0/block` => `sdb` 
`ls /sys/bus/scsi/devices/32:0:1:0/block` => `sda`
```
Disk /dev/sda: 16 GiB, 17179869184 bytes, 33554432 sectors
Disk model: Virtual disk
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk /dev/sdb: 5 GiB, 5368709120 bytes, …
```
=> scsi_volume_id_device_path_resolver flaky on ubuntu jammy

platform/net/ubuntu_net_manager.go
This reorder should help prevent cases in which the firewall rule for NATS cannot be setup due to missing connectivity
Resolves:
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/280
=> Reorder code to boradcast address earlier

infrastructure/devicepathresolver/id_device_path_resolver.go
as disk ids can be longer than 20 characters it seems strange that we put a limit on this. as that means that the disk-id glob search will never be found if it cuts of everything after 20 characters
=> remove the limit of characters for the device id

infrastructure/devicepathresolver/id_device_path_resolver.go, infrastructure/devicepathresolver/id_device_path_resolver_test.go, platform/linux_platform.go, platform/provider.go
Add a `StripVolumeRegex` configuration property that will be used to strip some part of `disk-id` (aka volume ID) before device path resolve step, as proposed by the Working Group:
_Create a configuration property for the bosh agent to configure a strip-volume-regex,
which would allow specifying a regex prefix per IaaS in the bosh stemcell builder [here](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/ubuntu-jammy/master/stemcell_builder/stages/bosh_alicloud_agent_settings/apply.sh#L11-L1) (in the case of Ali Cloud)._
The potential benefit is that this could solve issue #310.
=> Add StripVolumeRegex configuration property

docs/working_with_dev_versions.md
This PR provides suggestions on how to test local changes in the bosh-agent in development environments. Any feedback or ideas are welcome :)
=> Efficient development with the bosh-agent

platform/linux_platform.go, platform/linux_platform_test.go
Pass the --sparse to the tar create archive command used for disk resize. This option will detect holes in the file and only copy non-empty data. The --sparse option is omitted on the tar extraction command where it has no effect.
Fixes https://github.com/cloudfoundry/bosh-agent/issues/313
=> Support Linux sparse files

platform/disk/partitioner_interface.go, platform/disk/root_device_partitioner.go, platform/disk/root_device_partitioner_test.go
GCP repartition the root disks. It doesn't take in account if a system has more then 1 partition.
This has been tested with EFI stemcell and non EFI stemcell
=> Adding support for EFI based stemcells.

platform/net/kernel_ipv6.go, platform/net/kernel_ipv6_test.go
The introduction of the EFI (Extensible Firmware Interface) as a replacement of the BIOS (Basic Input/Output System) on the vSphere Jammy stemcell had an unintended consequence: any VM deployed with an IPv6 address became unresponsive.
The cause was the change of the location of the `grub.cfg` file: `/boot/grub/grub.cfg` → `/boot/efi/EFI/grub/grub.cfg`. The Agent needs to modify `grub.cfg` to remove the kernel commandline directive explicitly disallowing IPv6 (`ipv6.disable=1`).
The fix was simple: check the BIOS location, and if that fails, fall back to the EFI location.
Fixes, from `/var/vcap/bosh/log/current`:
```
ERROR - Agent exited with error: Running bootstrap: Setting up networking: Enabling IPv6 in kernel: Reading grub: Opening file /boot/grub/grub.cfg: open /boot/grub/grub.cfg: …
```
=> Allow EFI-enabled stemcells to boot with IPv6

platform/linux_platform.go, platform/linux_platform_test.go
cis wants nosuid on /home mount
`1.1.7.3 Ensure nosuid option set on /home partition`
=> fix for jammy cis 1.1.7.3

platform/net/kernel_ipv6_test.go
For some unknown reason even tho we were looping over two strings, the value that was tested was always the second string during both loops
Simply create two `When` clauses, one for each path
=> Remove the for-range in test setup

infrastructure/devicepathresolver/mapped_device_path_resolver.go, infrastructure/devicepathresolver/mapped_device_path_resolver_test.go
We'd like to use the idDevicePathResolver and disk hints instead, but we don't actually know the volume id for the ephemeral disk until the instance is created at which point it's too late to put the disk into into the metadata because the VM has to be in a stopped state to do that.
So instead, we just guess here and hope the nvme devices match up. Which isn't much worse than what we were doing before, but AWS was also just sort of hoping that the device would end up on /dev/sdb.
=> Noble VMs on AWS don't have /dev/sdX devices for some reason.

agent/bootstrap_test.go, platform/net/interface_configuration_creator.go, platform/net/interface_configuration_creator_test.go
Some iaas (e.g. AWS) support dual-stack network interface cards. However as bosh only supports to provide one range (either ipv4 or ipv6) in the cloud config two networks need to be defined to specify both ranges. Therefore the error message can be deleted.
=> Disable error messages related to networks/network interface cards

platform/net/ip/ip_resolver.go, platform/net/ip/ip_resolver_test.go
When resolving for IPv6 Addresses, in some cases the GetPrimaryIP method still returns IPv4 Addresses (Depending on the sorting of the Addresses on the network interface), because the To16() method just checks if the ip address is a valid ip address or not. Actually the To4() method is the correct one to use as it returns something if the ip address is Ipv4 and "nil" if the ip address is Ipv6. We introduced this with https://github.com/cloudfoundry/bosh-agent/pull/351 . We thought our unit test cases covered all scenarios, but missed this one. Added a separate test as well for this case.
=> Fix Network Resolution For IPv6 addresses

integration/windows/fixtures/psFixture/psFixture.psm1
cacls.exe is deprecated, and should be replaced with icacls.
We are seeing integration test failures coinciding with a Windows update that take the form:
```
[FAILED] Expected data directory to have correct ACLs. Counted 1 errors.
'Check-Acls C:\var\vcap\data\' command output: 
Adding 2016 ACLs
5
Error (C:\var\vcap\data\testfile): BUILTIN\Users,Allow
Expected
<bool>: false
to be true
```
Attempting to update this deprecated tool to see if that fixes the error.
=> Update Windows integration test fixture

ci/pipeline.yml, platform/windows_platform_test.go
- compare case insenstively when testing paths in case the OS has C:/WINDOWS instead of C:/Windows
- add a 2019 worker tag to make sure we are running on the right concourse worker
=> unit test fixes
