agent/action/get_state.go
agent/action/get_state_test.go
jobsupervisor/dummy_job_supervisor.go
jobsupervisor/dummy_nats_job_supervisor.go
jobsupervisor/fakes/fake_job_supervisor.go
jobsupervisor/job_supervisor_interface.go
jobsupervisor/monit/status.go
jobsupervisor/monit/status_interface.go
jobsupervisor/monit/status_test.go
jobsupervisor/monit_job_supervisor.go
jobsupervisor/monit_job_supervisor_test.go

[#100344708](https://www.pivotaltracker.com/story/show/100344708)
Signed-off-by: Hua Zhang <zhuadl@cn.ibm.com>

Director should include process's running states in vm state results.

---

jobsupervisor/dummy_nats_job_supervisor.go
jobsupervisor/job_supervisor_interface.go
jobsupervisor/monit/status.go
jobsupervisor/monit/status_interface.go
jobsupervisor/monit/status_test.go
jobsupervisor/monit_job_supervisor.go
jobsupervisor/monit_job_supervisor_test.go

[#100344890](https://www.pivotaltracker.com/story/show/100344890)
Signed-off-by: Zhou Xing <xingzhou@cn.ibm.com>

bosh cli should present the full details of the vm state

---

app/app_test.go
infrastructure/devicepathresolver/scsi.go
infrastructure/devicepathresolver/scsi_id_device_path_resolver.go
infrastructure/devicepathresolver/scsi_id_device_path_resolver_test.go
infrastructure/devicepathresolver/scsi_test.go
infrastructure/devicepathresolver/scsi_volume_id_device_path_resolver.go
infrastructure/devicepathresolver/scsi_volume_id_device_path_resolver_test.go
platform/provider.go
settings/settings.go
settings/settings_test.go

This PR contains a scsi-id device resolver. It will be used to discover disk using scsi-id.

Photon Adding a new scsi-id device resolver

---

agent/bootstrap_test.go
platform/cert/cert_manager.go
platform/cert/cert_manager_test.go
platform/dummy_platform.go
platform/provider.go

[#111476046](https://www.pivotaltracker.com/story/show/111476046)
Signed-off-by: Zhou Xing <xingzhou@cn.ibm.com>

retry and forcefully kill update-ca-certificates on ubuntu

---

platform/linux_platform.go
platform/linux_platform_test.go

Bosh agent will scrub ephemeral disk when upgrading stemcell
[issue #83](https://github.com/cloudfoundry/bosh-agent/issues/83)

Bosh agent will scrub ephemeral disk when upgrading stemcell

---

infrastructure/fakes/fake_settings_source.go
settings/retrieve_settings_retryable.go
settings/retrieve_settings_retryable_test.go
settings/service.go
settings/service_test.go

Make agent code more resilient, e.g. to handle temporary network issues
[#129348495](https://www.pivotaltracker.com/story/show/129348495)
Signed-off-by: Felix Riegger <felix.riegger@sap.com>

Retry getting agent settings

---

infrastructure/fakes/fake_settings_source.go
settings/retrieve_settings_retryable.go
settings/retrieve_settings_retryable_test.go
settings/service.go
settings/service_test.go

This change is already applied to master with this [pull request](https://github.com/cloudfoundry/bosh-agent/pull/96). We would like to have it merged here as well while we wait to the next stemcell release. We build an agent version with this change and verified that the retry logic works. 
[129348495](https://www.pivotaltracker.com/n/projects/1456570/stories/129348495)

Retry agent settings 257.x 3263.x

---

infrastructure/http_metadata_service.go
infrastructure/http_metadata_service_test.go

The PR is specific for SoftLayer because the content of user data returned by SoftLayer_Resource_Metadata service will contain escape characters, bosh-agent should strip or unquote it before unmarshalling. What follows is an example returned by SoftLayer_Resource_Metadata service:
"{\"registry\":{\"endpoint\":\"http:\/\/admin:admin@10.164.169.38:25777\"},\"server\":{\"name\":\"vm-adef6dd1-c536-4114-bc62-e02eac05a194\"},\"dns\":{}}"

Decode a string of user data which has been encoded using base-64 encoding by IaaS

---

bin/repack-stemcell/README.md
bin/repack-stemcell/repack.sh
bin/repack-stemcell/run.sh
bin/repack-stemcell/task.yml

cc @pivotal-jamil-shamy @tylerschultz @dpb587-pivotal

add useful testing script to quickly update stemcells with local agent binary

---

integration/ephemeral_disk_test.go
platform/disk/fakes/fake_disk_manager.go
platform/linux_platform.go
platform/linux_platform_test.go

[#150754334](https://www.pivotaltracker.com/story/show/150754334)

Partioning a root disk respects configured swap_size

---

agent/applier/concrete_applier.go
agent/applier/concrete_applier_test.go
agent/applier/packages/fakes/fake_applier.go
app/app.go
settings/settings.go
settings/settings_test.go

[#152414004](https://www.pivotaltracker.com/story/show/152414004)
Signed-off-by: Yulia Gaponenko <yulia.gaponenko1@de.ibm.com>

Download jobs and packages in parallel

---

agent/agent.go
agent/agent_test.go

This PR implements: https://www.pivotaltracker.com/story/show/174838726

Retry heartbeats after inital heartbeat has been send [#174838726]

---

.gitignore
platform/dummy_platform.go
platform/dummy_platform_test.go
platform/linux_platform.go
platform/linux_platform_test.go
platform/platform_interface.go
platform/platformfakes/fake_platform.go
platform/windows_platform.go
settings/settings.go
settings/settings_test.go

refactors https://github.com/cloudfoundry/bosh-agent/pull/234

Increase size of /var/vcap/data/sys/run and make configurable [#173506635]

---

.gitignore
platform/dummy_platform.go
platform/dummy_platform_test.go
platform/linux_platform.go
platform/linux_platform_test.go
platform/platform_interface.go
platform/platformfakes/fake_platform.go
platform/windows_platform.go
settings/settings.go
settings/settings_test.go

Reverts cloudfoundry/bosh-agent#236
Merged to wrong branch

Revert "Increase size of /var/vcap/data/sys/run and make configurable [#173506635]"

---

platform/linux_platform.go

Hello BOSH core devs!
As preliminary work to the upcoming PR that will fix the IaaS-native disk resizing (a story we are working on currently at SAP), here are some simple and straight-forward improvements made to the `MountPersistentDisk()` method code, that will address those issues:
- Variable names were badly describing what was put into it.
- The `realPath` (actually the disk device file in `/dev`) variable was reused at the end of the method in order to store something with a very different meaning: the path of the partition (in `/dev`) to mount.
Now the code reads better, and allow us to properly add things related to the IaaS-native disk resizing.
If you can review this quickly, we are waiting for it in order to rebase our next PR. Thanks!
Best,
Benjamin

Improve MountPersistentDisk() code for Linux platform

---

platform/linux_platform.go
platform/linux_platform_test.go

check if the lastlog file exists
as we already do this for `btmp` and `wtmp`

check if lastlog file exists

---

platform/net/firewall_provider_linux.go

on warden the nats fw feature breaks the agent start with
`2022-03-15_22:58:56.43738 [main] 2022/03/15 22:58:56 ERROR - Agent exited with error: Running bootstrap: Setting up networking: Setting up Nats Firewall: Error setting up cgroups for nats api access: cgroups: cgroup mountpoint does not exist`
add check if cgroups are mounted to the if that handles early returns.

Return early if v1 cgroups are not mounted

---

platform/net/firewall_provider_linux.go

currently a stemcell build with the agent will not be able to successfully
deploy since the iptables setup is trying to add v6 addresses via the v4 
api (using the binary iptables through the iptables lib) but in case of a
v6 target we need to use `ip6tables` .
This adds logic based on dns lookups to figure out if the target is using v4
or v6 and switched the creation of the `ipt` object to use the according ipVersion.

Add V6 iptables support

---

agent/action/drain_test.go
agent/applier/models/job_test.go
agent/bootstrap_test.go
main/agent.go
platform/cert/cert_manager_test.go
platform/dummy_platform.go
platform/dummy_platform_test.go
platform/linux_platform.go
platform/net/lock_file.go
platform/windows_platform.go

While not strictly a problem, double imports are bad form and confusing.

Remove double imports across the codebase

---

mbus/nats_handler.go

The additional logging that was added has shown that the agent eventually exits with the following error:
`ErrNoServers = errors.New("nats: no servers available for connection")` from the nats library.  
Additionally, the `c.Reconnects` counter didn't increment. It turns out setting `nats.RetryOnFailedConnect(true)`
option is also required to actually do reconnects not just retries.
Remove nats maxConnectionRetries and replace with indefinite retries. We don't actually want the agent to give up reconnecting. So it shouldn't ever run out of attempts on a longer than usual bosh recreate.
Add Arping to bosh address to make sure cache is not only flushed but also filled with right value on reconnect.
Currently the Arp resolution is probably done via the OS at some point and making it explicit …

Add finetuning to nats client settings. Make running bosh actions directly after a director recreate more reliable.

---

agent/logstarprovider/logs_tar_provider_test.go

When not running on Linux, we silently ignore requests for the "system" log type. We didn't account for this in the relevant test. This commit fixes that oversight.

Correctly test on non-Linux

---

main/compile.go

correctly compose stemcell slug with `bosh-agent compile`

---

releasetarball/compile.go
releasetarball/compile_test.go

fixes: https://github.com/cloudfoundry/bosh-agent/issues/323

fix(bosh-agent compile): fingerprint and dependency fields do not match source tarball

---

agentclient/fakes/fake_agent_client.go
platform/platformfakes/fake_platform.go

Generated using `go generate ./...`

Regenerate mocks

---

.github/workflows/go.yml
agent/bootstrap_test.go

Previous config was not running tests when a PR was opened.

Fix bootstrap unit tests and run tests for pull requests
